"""Updated foreign key in MLUserInput and adjusted relationships

Revision ID: aafc3deb5bf6
Revises: 0388196d5c0e
Create Date: 2024-02-01 16:30:10.194063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aafc3deb5bf6'
down_revision = '0388196d5c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_game_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=100), nullable=False),
    sa.Column('original_story', sa.Text(), nullable=False),
    sa.Column('final_story', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_user_input',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('placeholder_type', sa.String(length=50), nullable=False),
    sa.Column('original_word', sa.String(length=100), nullable=True),
    sa.Column('user_input', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['ml_game_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ml_user_input')
    op.drop_table('ml_game_session')
    # ### end Alembic commands ###
